# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 592c3c23f94d49301fad5b5257ef0d022b1b3261693084e28394d8af7abcc2d26eef31241ad319855cb62dd34855176257f4318c7d418cc5fd66128ba5160391

test:
  secret_key_base: 2d5c34130e44c5073ac9f3c859eac8c7e01044e6d9cef41ca1b03f480de5b7d9a348f2412d83f1058df5e8eb3de2f83a4a4604ba8b0abcd30553c08a11deb216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
